# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\home\lip_sync\rhubarb-lip-sync

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\home\lip_sync\rhubarb-lip-sync

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	"C:\Program Files\CMake\bin\cpack.exe" --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	"C:\Program Files\CMake\bin\cpack.exe" --config ./CPackSourceConfig.cmake C:/home/lip_sync/rhubarb-lip-sync/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\home\lip_sync\rhubarb-lip-sync\CMakeFiles C:\home\lip_sync\rhubarb-lip-sync\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\home\lip_sync\rhubarb-lip-sync\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named whereami

# Build rule for target.
whereami: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 whereami
.PHONY : whereami

# fast build rule for target.
whereami/fast:
	$(MAKE) -f rhubarb\CMakeFiles\whereami.dir\build.make rhubarb/CMakeFiles/whereami.dir/build
.PHONY : whereami/fast

#=============================================================================
# Target rules for targets named pocketSphinx

# Build rule for target.
pocketSphinx: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 pocketSphinx
.PHONY : pocketSphinx

# fast build rule for target.
pocketSphinx/fast:
	$(MAKE) -f rhubarb\CMakeFiles\pocketSphinx.dir\build.make rhubarb/CMakeFiles/pocketSphinx.dir/build
.PHONY : pocketSphinx/fast

#=============================================================================
# Target rules for targets named cppFormat

# Build rule for target.
cppFormat: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 cppFormat
.PHONY : cppFormat

# fast build rule for target.
cppFormat/fast:
	$(MAKE) -f rhubarb\CMakeFiles\cppFormat.dir\build.make rhubarb/CMakeFiles/cppFormat.dir/build
.PHONY : cppFormat/fast

#=============================================================================
# Target rules for targets named vorbis

# Build rule for target.
vorbis: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 vorbis
.PHONY : vorbis

# fast build rule for target.
vorbis/fast:
	$(MAKE) -f rhubarb\CMakeFiles\vorbis.dir\build.make rhubarb/CMakeFiles/vorbis.dir/build
.PHONY : vorbis/fast

#=============================================================================
# Target rules for targets named sphinxbase

# Build rule for target.
sphinxbase: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sphinxbase
.PHONY : sphinxbase

# fast build rule for target.
sphinxbase/fast:
	$(MAKE) -f rhubarb\CMakeFiles\sphinxbase.dir\build.make rhubarb/CMakeFiles/sphinxbase.dir/build
.PHONY : sphinxbase/fast

#=============================================================================
# Target rules for targets named ogg

# Build rule for target.
ogg: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ogg
.PHONY : ogg

# fast build rule for target.
ogg/fast:
	$(MAKE) -f rhubarb\CMakeFiles\ogg.dir\build.make rhubarb/CMakeFiles/ogg.dir/build
.PHONY : ogg/fast

#=============================================================================
# Target rules for targets named webRtc

# Build rule for target.
webRtc: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 webRtc
.PHONY : webRtc

# fast build rule for target.
webRtc/fast:
	$(MAKE) -f rhubarb\CMakeFiles\webRtc.dir\build.make rhubarb/CMakeFiles/webRtc.dir/build
.PHONY : webRtc/fast

#=============================================================================
# Target rules for targets named rhubarb-recognition

# Build rule for target.
rhubarb-recognition: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 rhubarb-recognition
.PHONY : rhubarb-recognition

# fast build rule for target.
rhubarb-recognition/fast:
	$(MAKE) -f rhubarb\CMakeFiles\rhubarb-recognition.dir\build.make rhubarb/CMakeFiles/rhubarb-recognition.dir/build
.PHONY : rhubarb-recognition/fast

#=============================================================================
# Target rules for targets named flite

# Build rule for target.
flite: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 flite
.PHONY : flite

# fast build rule for target.
flite/fast:
	$(MAKE) -f rhubarb\CMakeFiles\flite.dir\build.make rhubarb/CMakeFiles/flite.dir/build
.PHONY : flite/fast

#=============================================================================
# Target rules for targets named utfcpp

# Build rule for target.
utfcpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 utfcpp
.PHONY : utfcpp

# fast build rule for target.
utfcpp/fast:
	$(MAKE) -f rhubarb\CMakeFiles\utfcpp.dir\build.make rhubarb/CMakeFiles/utfcpp.dir/build
.PHONY : utfcpp/fast

#=============================================================================
# Target rules for targets named utf8proc

# Build rule for target.
utf8proc: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 utf8proc
.PHONY : utf8proc

# fast build rule for target.
utf8proc/fast:
	$(MAKE) -f rhubarb\CMakeFiles\utf8proc.dir\build.make rhubarb/CMakeFiles/utf8proc.dir/build
.PHONY : utf8proc/fast

#=============================================================================
# Target rules for targets named rhubarb-animation

# Build rule for target.
rhubarb-animation: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 rhubarb-animation
.PHONY : rhubarb-animation

# fast build rule for target.
rhubarb-animation/fast:
	$(MAKE) -f rhubarb\CMakeFiles\rhubarb-animation.dir\build.make rhubarb/CMakeFiles/rhubarb-animation.dir/build
.PHONY : rhubarb-animation/fast

#=============================================================================
# Target rules for targets named rhubarb-audio

# Build rule for target.
rhubarb-audio: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 rhubarb-audio
.PHONY : rhubarb-audio

# fast build rule for target.
rhubarb-audio/fast:
	$(MAKE) -f rhubarb\CMakeFiles\rhubarb-audio.dir\build.make rhubarb/CMakeFiles/rhubarb-audio.dir/build
.PHONY : rhubarb-audio/fast

#=============================================================================
# Target rules for targets named rhubarb-core

# Build rule for target.
rhubarb-core: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 rhubarb-core
.PHONY : rhubarb-core

# fast build rule for target.
rhubarb-core/fast:
	$(MAKE) -f rhubarb\CMakeFiles\rhubarb-core.dir\build.make rhubarb/CMakeFiles/rhubarb-core.dir/build
.PHONY : rhubarb-core/fast

#=============================================================================
# Target rules for targets named rhubarb-exporters

# Build rule for target.
rhubarb-exporters: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 rhubarb-exporters
.PHONY : rhubarb-exporters

# fast build rule for target.
rhubarb-exporters/fast:
	$(MAKE) -f rhubarb\CMakeFiles\rhubarb-exporters.dir\build.make rhubarb/CMakeFiles/rhubarb-exporters.dir/build
.PHONY : rhubarb-exporters/fast

#=============================================================================
# Target rules for targets named rhubarb-lib

# Build rule for target.
rhubarb-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 rhubarb-lib
.PHONY : rhubarb-lib

# fast build rule for target.
rhubarb-lib/fast:
	$(MAKE) -f rhubarb\CMakeFiles\rhubarb-lib.dir\build.make rhubarb/CMakeFiles/rhubarb-lib.dir/build
.PHONY : rhubarb-lib/fast

#=============================================================================
# Target rules for targets named rhubarb-logging

# Build rule for target.
rhubarb-logging: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 rhubarb-logging
.PHONY : rhubarb-logging

# fast build rule for target.
rhubarb-logging/fast:
	$(MAKE) -f rhubarb\CMakeFiles\rhubarb-logging.dir\build.make rhubarb/CMakeFiles/rhubarb-logging.dir/build
.PHONY : rhubarb-logging/fast

#=============================================================================
# Target rules for targets named rhubarb-time

# Build rule for target.
rhubarb-time: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 rhubarb-time
.PHONY : rhubarb-time

# fast build rule for target.
rhubarb-time/fast:
	$(MAKE) -f rhubarb\CMakeFiles\rhubarb-time.dir\build.make rhubarb/CMakeFiles/rhubarb-time.dir/build
.PHONY : rhubarb-time/fast

#=============================================================================
# Target rules for targets named rhubarb-tools

# Build rule for target.
rhubarb-tools: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 rhubarb-tools
.PHONY : rhubarb-tools

# fast build rule for target.
rhubarb-tools/fast:
	$(MAKE) -f rhubarb\CMakeFiles\rhubarb-tools.dir\build.make rhubarb/CMakeFiles/rhubarb-tools.dir/build
.PHONY : rhubarb-tools/fast

#=============================================================================
# Target rules for targets named rhubarb

# Build rule for target.
rhubarb: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 rhubarb
.PHONY : rhubarb

# fast build rule for target.
rhubarb/fast:
	$(MAKE) -f rhubarb\CMakeFiles\rhubarb.dir\build.make rhubarb/CMakeFiles/rhubarb.dir/build
.PHONY : rhubarb/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... package
	@echo ... install/strip
	@echo ... package_source
	@echo ... install/local
	@echo ... install
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... list_install_components
	@echo ... whereami
	@echo ... pocketSphinx
	@echo ... cppFormat
	@echo ... vorbis
	@echo ... sphinxbase
	@echo ... ogg
	@echo ... webRtc
	@echo ... rhubarb-recognition
	@echo ... flite
	@echo ... utfcpp
	@echo ... utf8proc
	@echo ... rhubarb-animation
	@echo ... rhubarb-audio
	@echo ... rhubarb-core
	@echo ... rhubarb-exporters
	@echo ... rhubarb-lib
	@echo ... rhubarb-logging
	@echo ... rhubarb-time
	@echo ... rhubarb-tools
	@echo ... rhubarb
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

